# Generated by Django 3.0.4 on 2020-03-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
