# Generated by Django 3.0.4 on 2020-03-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('core', '0003_auto_20200306_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='reviews',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
