# Generated by Django 3.0.4 on 2020-03-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('core', '0006_touristspot_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location'),
        ),
    ]
