# Generated by Django 3.0.4 on 2020-03-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200306_2002'),
        ('comments', '0001_initial'),
        ('perks', '0001_initial'),
        ('core', '0008_auto_20200309_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='comments.Comment'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='perks',
            field=models.ManyToManyField(blank=True, null=True, to='perks.Perk'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='reviews.Review'),
        ),
    ]
