# Generated by Django 3.0.4 on 2020-03-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('core', '0010_auto_20200309_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
